// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://akjxunfijvyajctpcdfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFranh1bmZpanZ5YWpjdHBjZGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwODk0NTMsImV4cCI6MjA1OTY2NTQ1M30.5O-JCbAxzqhHAHnw36sAP_eFYRryn8YdJCQmHpviXUQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);